Problems fixed for scroll bar accessibility issue
Vets-Who-Code/march2021 pull request #189
Opened 2021-04-03 04:15 UTC by djkalbert

<Problems>
1. The attempt to link “skip to content” feature to the arrow feature does not work. It’s not properly linked. It doesn’t function.
2. This attempt in the first place rejects the original purpose of the “skip to content” 
3. The arrow scroll bar behaves similar to the button but it’s actually div, so it doesn’t have any of the native accessibility features of the button. So this is an example of bad semantic html.

<Solution>
1. Go back to the original commit of skip to content directing to the actual content
2. Remove the div

2021-04-03 04:16 UTC, djkalbert commented
@dtetreau251

2021-04-03 11:59 UTC, dtetreau251 commented
readded the arrow but took out the tab index.  It should not break accessibility now.

2021-04-03 20:04 UTC, joeromine requested changes
Alber, the outline added to line 337 of the css removes the outline from the cards in Chrome and Firefox. Try and add a color and style to line 337 and you will see the outline again on the cards. ie: outline: 5px solid green;

2021-04-08 23:50 UTC, joeromine commented
Albert??  I'm closing this PR

2021-04-08 23:50 UTC, closed without merging